name: Continuous Integration

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        shell: bash
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}" \
            --password-stdin

      - name: Build Docker Image
        shell: bash
        run: |
          docker build \
            -t abhinav04/mercury:latest \
            --build-arg NEXT_PUBLIC_BEEFREE_ID="${{ secrets.NEXT_PUBLIC_BEEFREE_ID }}" \
            --build-arg NEXT_PUBLIC_BEEFREE_SECRET="${{ secrets.NEXT_PUBLIC_BEEFREE_SECRET }}" \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" \
            --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            .

      - name: Push Image to Docker Hub
        shell: bash
        run: |
          docker push abhinav04/mercury:latest
