name : DAG Workflow

on : workflow_dispatch

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run : echo "This is job 1 saying hi"
    job2:
        runs-on: ubuntu-latest
        steps: 
            - run : echo "This is job 2 saying hi"
    job3:
        runs-on: ubuntu-latest
        needs: 
            - job1
            - job2
        steps:
            - run : echo "This is job 3 saying hi"
    job4:
        runs-on: ubuntu-latest
        needs:
            - job3
        steps:
            - run : echo "This is job 4 saying hi"


